//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.04 at 04:28:11 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openmrs.module.xdsbrepository.ihe.iti.actors.transport.xds;
